services:
  mysql:
    image: mysql:8.4
    container_name: queueify-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: queueify
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: